#!/bin/bash
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# cleanup_cores.sh - Core Dump Cleanup Daemon
#
# Periodically removes core dump files generated by crashes to prevent
# storage abuse during long fuzzing campaigns.
# Run this in background with: nohup ./cleanup_cores.sh &

echo "Starting core file cleanup daemon..."
echo "Removing core* files every minute"
echo "Log file: cleanup_cores.log"

while true; do
    # Remove core files
    rm -f ./core*
    
    # Log the cleanup (optional)
    echo "$(date): Cleaned up core files" >> cleanup_cores.log
    
    # Sleep for 1 minute
    sleep 10
done 